# YAML Lint configuration
---
extends: default

rules:
  # Line length
  line-length:
    max: 120
    level: warning

  # Allow multiple documents
  document-start: disable

  # Allow comments on same line
  comments:
    min-spaces-from-content: 1

  # Indentation
  indentation:
    spaces: 2
    indent-sequences: true

  # Truthy values
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']

  # Brackets
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1

  # Braces
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1

  # Empty lines
  empty-lines:
    max: 2
    max-start: 0
    max-end: 1

# Ignore certain files
ignore: |
  .github/
  node_modules/
  venv/
  .venv/
